# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
use_frameworks!

target 'PeleMedicalCenter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Firebase/Core'
#  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'

 
  # Pods for PeleMedicalCenter
 target 'PeleMedicalCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PeleMedicalCenterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
